global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ '172.172.0.4:9100' ]

  - job_name: 'server'
    static_configs:
      - targets: [ '172.172.0.5:9200' ]

