name: Badges

on:
  push:
    branches:
      - main

jobs:
  update-badges:
    name: Update Badges
    if: "contains(github.event.commits[0].message, '[RUN_CI]')"
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Build and run ctest
       run: |
         pip uninstall conan -y
         pip install -U conan==1.59.0
         mkdir build 
         cd build
         conan install .. --build=missing -s build_type=Debug
         cmake -DCMAKE_BUILD_TYPE=Debug ..
         cmake --build .
         ctest | grep "#" > output.txt
         NAMES_=$(cat output.txt | awk -F 'Scenario:' '$2{print $2'} RS='.')
         RESULTS_=$(cat  output.txt | awk '{print $(NF-2)}')
         I=1
         IFS=$'\n'
         for n in $NAMES_; do
         echo "NAME_TEST_$I=TEST$n" >> $GITHUB_ENV
         I=$((I + 1))
         done
         I=1
         for r in $RESULTS_; do
         echo "VALUE_TEST_$I=$r" >> $GITHUB_ENV
         I=$((I + 1))
         done
     - name: Create Awesome Badge
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fa7d81fb0caaae8a2790c00d2a20c0d0
          filename: cmake_tests.json
          label: Weather is 
          message: Ok
          color: green
     #TODO: make badge creation for custom number of testest
       env:
         GIST_ID: fa7d81fb0caaae8a2790c00d2a20c0d0
     - name: Create Badge Test1
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fa7d81fb0caaae8a2790c00d2a20c0d0
          filename: test1.json
          label: ${{ env.NAME_TEST_1 }}
          message: ${{ env.VALUE_TEST_1 }}
     - name: Create Badge Test2
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fa7d81fb0caaae8a2790c00d2a20c0d0
          filename: test2.json
          label: ${{ env.NAME_TEST_2 }}
          message: ${{ env.VALUE_TEST_2 }}
     - name: Create Badge Test3
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fa7d81fb0caaae8a2790c00d2a20c0d0
          filename: test3.json
          label: ${{ env.NAME_TEST_3 }}
          message: ${{ env.VALUE_TEST_3 }}
     - name: Create Badge Test4
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fa7d81fb0caaae8a2790c00d2a20c0d0
          filename: test4.json
          label: ${{ env.NAME_TEST_4 }}
          message: ${{ env.VALUE_TEST_4 }}
           
