name: Restart

on:  
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Server to start:'
        required: true
        type: choice
        options:
        - 'olololo.lol'
        - 'test.srv'
      force_restart:
        description: 'Restart if already running'
        required: false
        type: boolean
jobs:
  start-yc-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get inputs for workflow and run
        env:
          SERVER_TO_START: ${{ inputs.server_name }}
          FORCE_RESTART: ${{ inputs.force_restart }}
          YC_TKN: ${{ secrets.YC_TOKEN }}
        run: |
          LOG="restart.yaml>"
          echo "$LOG Server to start: $SERVER_TO_START"
          echo "$LOG Force restart checkbox: $FORCE_RESTART"
          echo "$LOG install yc"
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /tmp/yc -n
          /tmp/yc/bin/./yc config set token $YC_TKN
          NEED_TO_START=true
          NEED_TO_STOP=false
          id=epdlpva9bbq9kp0euuhn
          status=$(/tmp/yc/bin/./yc compute instance get $id | awk -F: '$1 == "status" {print$2}')
          if [[ $status == " RUNNING" ]];then
          echo "$LOG Server $SERVER_TO_START is already running."
          NEED_TO_START=false
          if [[ $FORCE_RESTART == "true" ]]; then
          NEED_TO_START=true
          NEED_TO_STOP=true
          fi
          fi

          if [[ $NEED_TO_STOP == "true" ]];then
          /tmp/yc/bin/./yc compute instance stop $id > /dev/null
          wait $!
          echo "$LOG Server $SERVER_TO_START was stopped."
          fi

          if [[ $NEED_TO_START == "true" ]];then
          /tmp/yc/bin/./yc compute instance start $id > /dev/null
          wait $!
          echo "$LOG Server $SERVER_TO_START was started. Exit."
          else
          echo "$LOG Do not need to restart. Exit."
          fi

          
          
        
